title: OHDSI 粉丝团
description: OHDSI 粉丝团是一个汇总、分享与 OHDSI(跨机构跨学科的医学研究)相关理论方法知识经验的网站.旨在探索利用区块链技术来解决面向研究的患者就诊数据共享、研究方案、算法、成果传播、知识应用等各参与方的利益分配，实现人人可获益
github:
  is_project_page: false
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman